FROM eclipse-temurin:23-jre
WORKDIR /app

ARG OTEL_JAVA_AGENT_VERSION=2.27.0
COPY opentelemetry-javaagent.jar /otel/opentelemetry-javaagent.jar

COPY target/*-with-dependencies.jar /app/profile.jar

RUN useradd -M -u 1001 appuser && mkdir -p /var/log/account/profile && chown -R appuser:appuser /app /otel /var/log/account

USER appuser

EXPOSE 8080 9090

CMD ["java", "-jar", "/app/profile.jar"]
