apiVersion: v1
kind: Secret
metadata:
  name: account-secrets
  namespace: account
type: Opaque
stringData:
  POSTGRES_PASSWORD: CHANGE_ME_DATABASE_PASSWORD
  IDENTITY_DATABASE_PASSWORD: CHANGE_ME_DATABASE_PASSWORD
  IDENTITY_OTP_HMAC_SECRET: CHANGE_ME_AT_LEAST_32_RANDOM_CHARACTERS
  IDENTITY_INTERNAL_AUTH_SECRET: CHANGE_ME_AT_LEAST_32_RANDOM_CHARACTERS
  IDENTITY_SMTP_USERNAME: CHANGE_ME_SMTP_USERNAME
  IDENTITY_SMTP_PASSWORD: CHANGE_ME_SMTP_PASSWORD
  MINIO_ROOT_PASSWORD: CHANGE_ME_MINIO_PASSWORD
  IDENTITY_S3_SECRET_KEY: CHANGE_ME_MINIO_PASSWORD
---
apiVersion: v1
kind: Secret
metadata:
  name: account-jwt-keys
  namespace: account
type: Opaque
stringData:
  account-jwt-private.pem: |
    REPLACE_WITH_RSA_PRIVATE_KEY
  account-jwt-public.pem: |
    REPLACE_WITH_RSA_PUBLIC_KEY
