global:
  storageClass: ""

signoz:
  image:
    tag: v0.127.1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 1Gi
  persistence:
    enabled: true
    size: 5Gi

otelCollector:
  image:
    tag: v0.144.5
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      memory: 2Gi

clickhouse:
  image:
    tag: 25.5.6
  persistence:
    enabled: true
    size: 100Gi
  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      memory: 8Gi
  zookeeper:
    persistence:
      enabled: true
      size: 8Gi
